apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app-one
  name: app-one
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app-one

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app-two
  name: app-two
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app-two

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app-three
  name: app-three
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app-three
