apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-one
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-one
    spec:
      containers:
        - image: paulbouwer/hello-kubernetes:1.10
          name: hello-kubernetes
          env:
            - name: MESSAGE
              value: "Hello from app1."

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-two
  name: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-two
    spec:
      containers:
        - image: paulbouwer/hello-kubernetes:1.10
          name: hello-kubernetes
          env:
            - name: MESSAGE
              value: "Hello from app2."

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-three
  name: app-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-three
    spec:
      containers:
        - image: paulbouwer/hello-kubernetes:1.10
          name: hello-kubernetes
          env:
            - name: MESSAGE
              value: "Hello from app3."
